### ISSUE TITLE
ev3 Buttons wait_for_bump 

### ISSUE THREAD

**Issue by dickric** [ev3dev/ev3dev.github.io#407]
Hello,

how can I use the Objekt "wait_for_bump" in the Button Class.
I become the following Errormessage. 

Wait for Bump
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    btnb.wait_for_bump(left, 500)
  File "/usr/lib/python3/dist-packages/ev3dev2/button.py", line 203, in wait_for_bump
    if self.wait_for_pressed(buttons, timeout_ms):
  File "/usr/lib/python3/dist-packages/ev3dev2/button.py", line 191, in wait_for_pressed
    return self._wait(buttons, [], timeout_ms)
  File "/usr/lib/python3/dist-packages/ev3dev2/button.py", line 168, in _wait
    for event in self.evdev_device.read_loop():
  File "/usr/lib/python3/dist-packages/ev3dev2/button.py", line 122, in evdev_device
    if device.name == self.evdev_device_name:
AttributeError: 'ButtonBase' object has no attribute 'evdev_device_name'

**Comment by WasabiFan** [comment]
This repository is for the ev3dev.org website, but I think your issue is about the Python library. Please open an issue there instead: https://github.com/ev3dev/ev3dev-lang-python/issues

**Comment by WasabiFan** [comment]
closed in favor of https://github.com/ev3dev/ev3dev-lang-python/issues/584
